re-instate IBIS_HUB, so that you can run ibis_controlhub separately from the ibis nameserver

diff --git a/scripts/ibis_nameserver b/scripts/ibis_nameserver
--- a/scripts/ibis_nameserver
+++ b/scripts/ibis_nameserver
@@ -1,20 +1,16 @@
 JAVACLASSPATH=$CLASSPATH:$IBIS_ROOT/build:
 
 # Ibis Hub controller
-# if [ "x$IBIS_HUB" != "x" ]; then
-#   # decode Ibis control hub reference
-#   HUB_HOST=`echo $IBIS_HUB|cut -f 1 -d :`
-#   HUB_PORT=`echo $IBIS_HUB|cut -f 2 -d :`
-#   echo "Name service will connect to Ibis hub:"
-#   echo "  ${HUB_HOST}:${HUB_PORT}"
-#   Dhub="-Dibis.connect.enable -Dibis.connect.control_links=RoutedMessages -Dibis.connect.data_links=PlainTCP -Dibis.connect.hub_host=$HUB_HOST -Dibis.connect.hub_port=$HUB_PORT"
-# else
-#   Dhub=
-# fi
-# No IBIS_HUB anymore: controlhub is now integrated within the nameserver,
-# with the -controlhub flag.
-
-Dhub=
+if [ "x$IBIS_HUB" != "x" ]; then
+  # decode Ibis control hub reference
+  HUB_HOST=`echo $IBIS_HUB|cut -f 1 -d :`
+  HUB_PORT=`echo $IBIS_HUB|cut -f 2 -d :`
+  echo "Name service will connect to Ibis hub:"
+  echo "  ${HUB_HOST}:${HUB_PORT}"
+  Dhub="-Dibis.connect.enable -Dibis.connect.control_links=RoutedMessages -Dibis.connect.data_links=PlainTCP -Dibis.connect.hub_host=$HUB_HOST -Dibis.connect.hub_port=$HUB_PORT"
+else
+  Dhub=
+fi
 
 for i in $*
 do
@@ -27,6 +23,12 @@ do
 	# work. However, the nameserver only uses control_links, so the
 	# contents for data_links does not really matter, as long as the
 	# socket type exists.
+	case x$IBIS_HUB in
+	x)	;;
+	*)	echo "You cannot use both -controlhub and the IBIS_HUB environment variable" 1>&2
+		;;
+	esac
+
 	Dhub="$Dhub -Dibis.connect.enable -Dibis.connect.control_links=RoutedMessages -Dibis.connect.data_links=PlainTCP -Dibis.name_server.host=`hostname -f`"
 	;;
     esac
